### ISSUE TITLE
请问什么时候可以下载预训练模型呢

### ISSUE THREAD

**Issue by yazheng0307** [ssocean/AlphX-Code-For-DAR#2]

**Comment by ssocean** [comment]
![image](https://user-images.githubusercontent.com/48676611/210701637-b87f5b42-8f7b-4d14-8c65-ac6374249d98.png)
你好，下载链接里从上到下第一个是CRNN的权重，第二第三个是对应检测器的权重，第四个是顺序预测U-Net的权重。
下载链接：https://pan.baidu.com/s/1sxxEkd7EpQ92wsGDhcU3RQ 
提取码：3n06

**Comment by SpiritBear000** [comment]
> ![image](https://user-images.githubusercontent.com/48676611/210701637-b87f5b42-8f7b-4d14-8c65-ac6374249d98.png) 你好，下载链接里从上到下第一个是CRNN的权重，第二第三个是对应检测器的权重，第四个是顺序预测U-Net的权重。 下载链接：https://pan.baidu.com/s/1sxxEkd7EpQ92wsGDhcU3RQ 提取码：3n06

作者您好，感谢您分享这一杰出的工作！上面这个链接失效了好像，不知道方不方便更新一下。:smile:

**Comment by ssocean** [comment]
好的~
链接：https://pan.baidu.com/s/1AOeOyK9LJy7zQsVOBqn_sg?pwd=w6wi 
提取码：w6wi
