### ISSUE TITLE
两个问题请求赐教

### ISSUE THREAD

**Issue by haooxia** [ssocean/AlphX-Code-For-DAR#3]
1. 请问码表`char.txt`接近1万个汉字是依据什么得到的？是大赛直接给定的吗？
2. 请问该比赛的数据集有公开吗？

**Comment by ssocean** [comment]
1.char.txt是可以根据label统计得到的（大赛好像也提供了码表）。
2.因为我不太清楚大赛是否允许选手二次分发数据，因此很抱歉我们不便提供。但是我们在参赛的时候注意到了与大赛数据集相似的开源数据集，repo地址：https://github.com/HCIILAB/TKH_MTH_Datasets_Release

**Comment by haooxia** [comment]
> 1.char.txt是可以根据label统计得到的（大赛好像也提供了码表）。 2.因为我不太清楚大赛是否允许选手二次分发数据，因此很抱歉我们不便提供。但是我们在参赛的时候注意到了与大赛数据集相似的开源数据集，repo地址：https://github.com/HCIILAB/TKH_MTH_Datasets_Release

好的，谢谢您

**Comment by SpiritBear000** [comment]
我在这个[链接](https://aistudio.baidu.com/projectdetail/6842909)里找到了码表，不知道是不是，分享一下大家看看。
本次比赛提供码表（下载链接见链接: https://pan.baidu.com/s/16wUeSZ4JKD6f1Pj9ZhlKww 提取码: i53n ），其中包含了初赛训练集、验证集**(初赛A榜)及测试集（初赛B榜）中出现的字符类别
