### ISSUE TITLE
这个比赛的数据集在哪下载

### ISSUE THREAD

**Issue by dreamlychina** [ssocean/AlphX-Code-For-DAR#4]
感谢分享代码和方案，想问下大佬，这个比赛的数据集现在可以在哪下载？？

**Comment by ssocean** [comment]
感谢关注~比赛官方的数据集现在我们也不知道在哪里可以下载，但是你可以从这两个地址找到和官方数据集非常相似的数据集[数据集1](https://github.com/HCIILAB/TKH_MTH_Datasets_Release)、[数据集2](https://github.com/HCIILAB/MTHv2_Datasets_Release)

**Comment by dreamlychina** [comment]
感谢大佬分享

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年02月11日 17:05 |
| 收件人 | ssocean/AlphX-Code-For-DAR ***@***.***> |
| 抄送人 | dreamlychina ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [ssocean/AlphX-Code-For-DAR] 这个比赛的数据集在哪下载 (Issue #4) |

感谢关注~比赛官方的数据集现在我们也不知道在哪里可以下载，但是你可以从这两个地址找到和官方数据集非常相似的数据集数据集1、数据集2
