### ISSUE TITLE
询问大佬几个问题？

### ISSUE THREAD

**Issue by dreamlychina** [ssocean/AlphX-Code-For-DAR#5]
（1）针对古籍的数据集，你们除了实验pannet++，还试过别的网络？？
（2）你们没有使用pannet++的识别分支，那为什么不直接使用pannet（我对pannet++不了解，望见谅）？？
（3）还有排序模块用unet，这个作用是啥？？
忘大佬抽空解答下，再次表示感谢。

**Comment by ssocean** [comment]
1. 我们没有尝试其它模型，但是你可以试试[SOLOv2: Dynamic and Fast Instance Segmentation]这篇工作，或者是看看近几年的SOTA，应该都会有比较不错的结果。
2. PAN加上识别分支其实就是PAN++，但是在实现上，PAN++的代码更稳定一些。
3. 因为古籍图像一整页的文本块顺序很难依靠简单的规则确定，但是如果把一整页的文本块分成不同的区域，再对区域里的文本块进行排序就相对容易些。UNET在这里就是对【不同的区域】进行排序的。即先对大区域排序，再对小区域排序，最后组合结果。

**Comment by dreamlychina** [comment]
感谢大佬百忙之中给予答复。

**Comment by ssocean** [comment]
客气客气~
