### ISSUE TITLE
大佬，我想问下你的font下面有两个字体，哪一个是繁体字的字体？？

### ISSUE THREAD

**Issue by dreamlychina** [ssocean/AlphX-Code-For-DAR#6]
感谢分享代码，想问下大佬，下面两个，那个是你demo图片中的字体？？SIMSUN.TTC好像不是。另一个是的？？问题有点蠢，还希望不要嘲笑。
NotoSansCJK-Regular.ttc
SIMSUN.TTC

**Comment by ssocean** [comment]
这个我也忘记了T.T SIMSUN是宋体，可能不支持繁体汉字。NotoSansCJK-Regular.ttc支持的范围会大一些，你可以试试这个。这个文件很容易下载到的，你可以去网上找找好看的字体文件，直接替换即可~
